import React, { useState, useEffect } from "react";
import {
  Container,
  Button,
  Table,
  Offcanvas,
  ListGroup,
  Spinner,
  Alert,
} from "react-bootstrap";
import {
  House,
  People,
  FileText,
  BoxArrowRight,
  Download,
} from "react-bootstrap-icons";
import { useNavigate } from "react-router-dom";
import axios from "axios";

const FacilityReportsPage = () => {
  const [showMenu, setShowMenu] = useState(false);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const navigate = useNavigate();

  const handleShowMenu = () => setShowMenu(true);
  const handleCloseMenu = () => setShowMenu(false);

  const handleLogout = () => {
    localStorage.removeItem("accessToken");
    navigate("/facility-admin/login");
  };

  const fetchReports = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("accessToken");
      const res = await axios.get(
        "http://127.0.0.1:8000/api/facilityadmin/list-facility-reports/",
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setReports(res.data);
      setLoading(false);
    } catch (err) {
      console.error(err);
      setError("Failed to load reports.");
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  return (
    <>
      <Offcanvas show={showMenu} onHide={handleCloseMenu}>
        <Offcanvas.Header closeButton>
          <Offcanvas.Title>Menu</Offcanvas.Title>
        </Offcanvas.Header>
        <Offcanvas.Body>
          <ListGroup variant="flush">
            <ListGroup.Item action href="/facility-admin/dashboard">
              <House /> Home
            </ListGroup.Item>
            <ListGroup.Item action href="/facility-admin/healthcare-workers">
              <People /> Healthcare Workers
            </ListGroup.Item>
            <ListGroup.Item action href="/facility-admin/reports">
              <FileText /> Facility Reports
            </ListGroup.Item>
            <ListGroup.Item action onClick={handleLogout}>
              <BoxArrowRight /> Logout
            </ListGroup.Item>
          </ListGroup>
        </Offcanvas.Body>
      </Offcanvas>

      <div className="bg-primary text-white p-3 d-flex justify-content-between align-items-center">
        <h3>Facility Reports</h3>
        <Button variant="light" onClick={handleShowMenu}>
          &#9776; Menu
        </Button>
      </div>

      <Container className="py-4">
        {loading && (
          <div className="text-center py-4">
            <Spinner animation="border" />
          </div>
        )}
        {error && <Alert variant="danger">{error}</Alert>}

        {!loading && !error && (
          <Table bordered hover>
            <thead>
              <tr>
                <th>Type</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Download</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id}>
                  <td>{r.report_type}</td>
                  <td>{r.generated_by}</td>
                  <td>{new Date(r.generated_at).toLocaleString()}</td>
                  <td>
                    <a
                      href={r.report_file}
                      className="btn btn-sm btn-primary"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <Download /> Download
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Container>
    </>
  );
};

export default FacilityReportsPage;
