# Generated by Django 5.2.3 on 2025-06-24 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facilityadmin', '0001_initial'),
        ('Sysadmin', '0004_facilityadmin_admin_username_facilityadmin_fullname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('birth_height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to='Facilityadmin.healthcarew')),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.vaccine')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='HealthcareW.child')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'National ID must contain only numbers')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Guardian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='HealthcareW.guardian'),
        ),
        migrations.CreateModel(
            name='HealthcareWorkerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WEEK_BEFORE', 'One Week Before'), ('TWO_DAYS_BEFORE', 'Two Days Before'), ('MISSED_APPOINTMENT', 'Missed Appointment')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='HealthcareW.appointment')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthcareW.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_type', models.CharField(choices=[('WEIGHT_AGE', 'Weight for Age'), ('HEIGHT_AGE', 'Height for Age'), ('WEIGHT_HEIGHT', 'Weight for Height')], max_length=20)),
                ('percentile', models.DecimalField(decimal_places=2, help_text="Child's percentile (0-100)", max_digits=5)),
                ('z_score', models.DecimalField(decimal_places=2, help_text='Standard deviation from mean', max_digits=5)),
                ('date_calculated', models.DateField()),
                ('is_normal_range', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_curves', to='HealthcareW.child')),
            ],
            options={
                'unique_together': {('child', 'curve_type', 'date_calculated')},
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='HealthcareW.child')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('child', 'date_recorded')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccination_record_ID', models.CharField(max_length=20, unique=True)),
                ('date_administered', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('dose_number', models.IntegerField()),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='HealthcareW.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.vaccine')),
            ],
            options={
                'ordering': ['-date_administered'],
                'unique_together': {('child', 'vaccine', 'dose_number')},
            },
        ),
    ]
