# Generated by Django 5.2.3 on 2025-07-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='child',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='child',
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='child',
        ),
        migrations.RemoveField(
            model_name='growthcurve',
            name='child',
        ),
        migrations.AlterUniqueTogether(
            name='growthcurve',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='growthrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='healthcareworkersession',
            name='healthcare_worker',
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='administered_by',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vaccine',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='GrowthCurve',
        ),
        migrations.DeleteModel(
            name='GrowthRecord',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='HealthcareWorkerSession',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
    ]
