# Generated by Django 5.2.3 on 2025-07-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareW', '0002_remove_notification_appointment_and_more'),
    ]

    def forwards(self, schema_editor):
        """No-op forward migration"""
        pass

    def backwards(self, schema_editor):
        """No-op backward migration"""
        pass

    operations = [
        migrations.RunPython(forwards, backwards),
    ]