# Generated by Django 5.2.3 on 2025-06-24 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sysadmin', '0004_facilityadmin_admin_username_facilityadmin_fullname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('vaccination_coverage', 'Vaccination Coverage'), ('child_registration', 'Child Registration'), ('growth_monitoring', 'Growth Monitoring'), ('overdue_vaccinations', 'Overdue Vaccinations')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='facility_reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareW',
            fields=[
                ('worker_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=15)),
                ('temporary_password', models.CharField(max_length=120)),
                ('password_changed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Facility_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_workers', to='Sysadmin.facilityadmin')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='Sysadmin.healthfacility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'healthcare_workers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Account Created'), ('activated', 'Account Activated'), ('deactivated', 'Account Deactivated'), ('updated', 'Details Updated'), ('password_changed', 'Password Changed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sysadmin.facilityadmin')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='Facilityadmin.healthcarew')),
            ],
            options={
                'db_table': 'worker_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
