# Generated by Django 5.2.3 on 2025-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcarew',
            old_name='username',
            new_name='worker_username',
        ),
    ]
