# Generated by Django 5.2.3 on 2025-07-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0002_rename_username_healthcarew_worker_username'),
        ('HealthcareW', '0002_remove_notification_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcarew',
            name='Facility_admin',
        ),
        migrations.RemoveField(
            model_name='healthcarew',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='healthcarew',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workeractivitylog',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workeractivitylog',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='FacilityReport',
        ),
        migrations.DeleteModel(
            name='HealthcareW',
        ),
        migrations.DeleteModel(
            name='WorkerActivityLog',
        ),
    ]
