# Generated by Django 5.2.3 on 2025-06-21 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='ID',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='FacilityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
