# Generated by Django 5.2.3 on 2025-06-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0002_alter_healthfacility_id_facilityadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='diseasePrevented',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='recommended_age',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='updated_at',
        ),
    ]
