# Generated by Django 5.2.3 on 2025-06-24 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0003_remove_vaccine_created_at_remove_vaccine_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityadmin',
            name='admin_username',
            field=models.CharField(default='Admin', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='facilityadmin',
            name='fullname',
            field=models.CharField(default='Fac_admin', max_length=120),
        ),
        migrations.AddField(
            model_name='facilityadmin',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facilityadmin',
            name='temporary_password',
            field=models.CharField(default='K-changeme123', max_length=128),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_vaccines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='diseasePrevented',
            field=models.CharField(default='Tuberculosis', max_length=100),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dosage',
            field=models.CharField(default='1 dose', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='facility',
            field=models.ManyToManyField(related_name='vaccines', to='Sysadmin.healthfacility'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='recommended_age',
            field=models.CharField(default='at birth', max_length=20),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('FACILITY_ADMIN', 'Facility Administrator'), ('HEALTHCARE WORKER', 'Worker'), ('GUARDIAN', 'Guardian')], default='GUARDIAN', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('facility_created', 'Facility Created'), ('facility_updated', 'Facility Updated'), ('facility_deactivated', 'Facility Deactivated'), ('admin_created', 'Facility Admin Created'), ('admin_updated', 'Facility Admin Updated'), ('vaccine_created', 'Vaccine Created'), ('vaccine_updated', 'Vaccine Updated'), ('report_generated', 'Report Generated')], max_length=30)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
