# Generated by Django 5.2.3 on 2025-06-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0004_facilityadmin_admin_username_facilityadmin_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_vaccines', to=settings.AUTH_USER_MODEL),
        ),
    ]
