# Generated by Django 5.2.3 on 2025-06-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0005_alter_vaccine_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vaccines', to=settings.AUTH_USER_MODEL),
        ),
    ]
