# Generated by Django 5.2.3 on 2025-06-26 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0007_alter_vaccine_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityadmin',
            name='admin_username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='facilityadmin',
            name='fullname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='facilityadmin',
            name='temporary_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vaccines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='diseasePrevented',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='recommended_age',
            field=models.CharField(max_length=20),
        ),
    ]
