# Generated by Django 5.2.3 on 2025-07-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0003_remove_healthcarew_facility_admin_and_more'),
        ('Sysadmin', '0008_alter_facilityadmin_admin_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemactivitylog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='systemreport',
            name='generated_by',
        ),
        migrations.DeleteModel(
            name='FacilityAdmin',
        ),
        migrations.DeleteModel(
            name='SystemActivityLog',
        ),
        migrations.DeleteModel(
            name='SystemReport',
        ),
    ]
